# Default values for clever-kubernetes-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

networkPolicy:
  enabled: false
  ingress:
  - {}
  egress:
  - {}

replicaCount: 1

image:
  repository: clevercloud/clever-kubernetes-operator
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3e427f3bb10071bd95811ba74a6a71bd247a8fb7"

# Declare your secrets for the operator to create add-ons on Clever Cloud
config:
  token: ""
  secret: ""
  # Leave both empty to use the public Clever Tools consumer, set them to use
  # your own OAuth consumer application.
  consumerKey: ""
  consumerSecret: ""

podDisruptionBudget:
  enabled: false
  minAvailable: 0

serviceAccount:
  # Specifies whether a service account should be created
  create: true

podAnnotations: {}

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsGroup: 25000
  runAsUser: 20000
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    memory: 64M
    cpu: 100m
    ephemeral-storage: 128Mi
  limits:
    memory: 64M
    cpu: 100m
    ephemeral-storage: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


