---
apiVersion: v1
kind: Secret
metadata:
{{ include "cleveroperator.namespace" . | indent 2 }}
  name: clever-kubernetes-operator-configuration
type: Opaque
stringData:
  config.toml: |
    [api]
    {{- if .Values.config.endpoint }}
    endpoint = "{{ .Values.config.endpoint }}"
    {{- end }}
    {{- if .Values.config.caBundle }}
    ca_bundle = "/etc/clever-kubernetes-operator-ca/ca-bundle.pem"
    {{- end }}
    token = "{{ .Values.config.token }}"
    secret = "{{ .Values.config.secret }}"
    {{- if .Values.config.consumerKey }}
    consumer-key = "{{ .Values.config.consumerKey }}"
    {{- end }}
    {{- if .Values.config.consumerSecret }}
    consumer-secret = "{{ .Values.config.consumerSecret }}"
    {{- end }}
