---
apiVersion: api.clever-cloud.com/v1
kind: Cellar
metadata:
  namespace: default
  name: cellar
spec:
  organisation: orga_<uuid v4>
  instance:
    region: par
    plan: s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: debian-cellar
  name: debian-cellar
  namespace: default
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debian-cellar
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: debian-cellar
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debian-cellar
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debian-cellar
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: debian-cellar
  labels:
    app: debian-cellar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-cellar
  template:
    metadata:
      labels:
        app: debian-cellar
    spec:
      serviceAccountName: debian-cellar
      automountServiceAccountToken: true
      containers:
        - image: debian:bullseye-slim
          imagePullPolicy: Always
          name: debian-cellar
          command:
            - "sleep"
            - "3600"
          env:
            - name: CELLAR_ADDON_HOST
              valueFrom:
                secretKeyRef:
                  name: cellar-secrets
                  key: CELLAR_ADDON_HOST
            - name: CELLAR_ADDON_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cellar-secrets
                  key: CELLAR_ADDON_KEY_ID
            - name: CELLAR_ADDON_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: cellar-secrets
                  key: CELLAR_ADDON_KEY_SECRET
          resources:
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 64M
              cpu: 100m
